// This script is now a no-op since vite-plugin-pwa handles service worker generation
// Kept for backward compatibility with existing npm scripts

console.log('✅ Service Worker generated by vite-plugin-pwa');
console.log('📦 No additional injection needed - sw.ts compiled automatically');
