// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

// Use hardcoded values for reliability in standalone mode
const SUPABASE_URL = "https://shydpfwuvnlzdzbubmgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoeWRwZnd1dm5semR6YnVibWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzM1MjcsImV4cCI6MjA2NzU0OTUyN30.l_PAPBy1hlb4J-amKx7qPJ1lPIFseA9GznwL6CcyaQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Completely defer initialization to prevent vendor bundle issues
let supabaseClient: any = null;
let isInitialized = false;
let initPromise: Promise<any> | null = null;

// Safe client getter that handles initialization
export const getSupabaseClient = async () => {
  if (supabaseClient && isInitialized) {
    return supabaseClient;
  }
  
  if (initPromise) {
    return initPromise;
  }
  
  if (typeof window === 'undefined') {
    return null; // No client in SSR
  }

  initPromise = new Promise(async (resolve, reject) => {
    try {
      // Wait for DOM to be ready
      if (document.readyState === 'loading') {
        await new Promise(resolve => {
          document.addEventListener('DOMContentLoaded', resolve, { once: true });
        });
      }
      
      // Dynamic import to prevent module-time execution
      const { createClient } = await import('@supabase/supabase-js');
      
      supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        }
      });
      
      isInitialized = true;
      console.log('✅ Supabase client initialized successfully');
      resolve(supabaseClient);
    } catch (error) {
      console.error('❌ Failed to create Supabase client:', error);
      reject(error);
    }
  });
  
  return initPromise;
};

// Legacy export - completely safe proxy that doesn't initialize anything
export const supabase = new Proxy({} as any, {
  get(target, prop) {
    console.warn('⚠️ Direct supabase access detected. Use getSupabaseClient() instead.');
    return () => {
      throw new Error('Use getSupabaseClient() for safe initialization');
    };
  }
});
